### ISSUE TITLE
Recommended Env variables for testnet

### ISSUE THREAD

**Issue by guirkgumbo** [solidex-fantom/solidly-ui#2]
I am looking to help with solidly-ui. I am trying to get a good dev setup going and it looks like a couple envs are required.

`NEXT_PUBLIC_CHAINID=4002
NEXT_PUBLIC_API=https://api.solidly.exchange`

I'm not sure what the NEXT_PUBLIC_API variable should be for running locally/testnet? Spin our own? Tried seeing what the https://testnet.solidly.exchange/ was doing but doesn't appear to be up and running.
Any recommendations?

**Comment by ghost** [comment]
@guirkgumbo Would be great to build the own API, I will be building it soon

**Comment by guirkgumbo** [comment]
> @guirkgumbo Would be great to build the own API, I will be building it soon

@ayanamidev Wanna collaborate on building one out? Sounds like fun.
